version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: travelplanner
      POSTGRES_USER: travelplanner
      POSTGRES_PASSWORD: travelplanner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: traver-planner:latest
    container_name: travel-planner
    environment:
      DB_HOST: postgres
      DB_NAME: travelplanner
      DB_USER: travelplanner
      DB_PASS: travelplanner
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
