version: "3"

includes:
  db: taskfiles/db.yml
  docker: taskfiles/docker.yml
  go: taskfiles/go.yml

tasks:
  run:
    deps:
      - go:tidy
      - docker:up
    cmds:
      - docker logs -f travel-planner

  stop:
    deps:
      - docker:down

  lint:
    deps:
      - go:lint

  mock:
    deps:
      - go:mock

  test:
    deps:
      - go:test

  coverage:
    deps:
      - go:coverage

  check:
    deps:
      - go:tidy
      - go:test
      - go:lint
