version: "3"

includes:
  docker: taskfiles/docker.yml
  go: taskfiles/go.yml

tasks:
  run:
    deps:
      - go:tidy
      - docker:up

  stop:
    deps:
      - docker:down

  lint:
    deps:
      - go:lint

  mock:
    deps:
      - go:mock

  test:
    deps:
      - go:test

  coverage:
    deps:
      - go:coverage
