version: "3"

includes:
  db: taskfiles/db.yml
  docker: taskfiles/docker.yml
  go: taskfiles/go.yml
  graph: taskfiles/graph.yml

tasks:
  run:
    deps:
      - go:tidy
      - go:dotenv
      - docker:setup
    cmds:
      - ./bin/docker-compose -f config/local/docker-compose.yml up -d --remove-orphans
      - godotenv -f ./config/local/.env go run main.go

  stop:
    deps:
      - docker:setup
    cmds:
      - ./bin/docker-compose -f config/local/docker-compose.yml down

  check:
    deps:
      - stop
      - go:tidy
      - go:test
      - go:lint
      - db:test
