version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: travelplanner
      POSTGRES_USER: travelplanner
      POSTGRES_PASSWORD: travelplanner
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local

  wait:
    image: waisbrot/wait
    container_name: wait
    environment:
      TIMEOUT: 600
    depends_on:
      - postgres
    networks:
      - local

  # app:
  #   build:
  #     context: .
  #   image: traver-planner:latest
  #   container_name: travel-planner
  #   environment:
  #     DB_HOST: postgres
  #     DB_NAME: travelplanner
  #     DB_USER: travelplanner
  #     DB_PASS: travelplanner
  #   depends_on:
  #     - wait
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - local

volumes:
  pgdata:

networks:
  local:
    name: local
    driver: bridge
