name: Run Tests on Master Push

on:
    push:
        branches:
        - master

jobs:
    test:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Install Taskfile
          run: |
            curl -sL https://taskfile.dev/install.sh | sh
            ls -al
            pwd
            echo 'export PATH=$PATH:$HOME/.task/bin' >> $HOME/.bashrc
            source $HOME/.bashrc
  
        - name: Run tests
          run: task test
