name: Run Tests on Master Push

on:
    push:
        branches:
        - master

jobs:
    test:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2.5.0

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.20
  
        - name: Install Taskfile
          run: |
            curl -sL https://taskfile.dev/install.sh | sh
  
        - name: Run tests
          run: ./bin/task go:test
